var c = document.getElementById("titleCanvas").getContext("2d");
var ctx = c.getContext("2d");
ctx.beginPath();
ctx.moveTo(0,0);
ctx.lineTo(450,0);
ctx.lineTo(250,100);
ctx.lineTo(0,100);
ctx.closePath();
ctx.fillStyle = "#EFFE17";
ctx.fill();
ctx.stroke();
ctx.beginPath();
ctx.moveTo(451,0);
ctx.lineTo(999,0);
ctx.lineTo(799,100);
ctx.lineTo(251,100);
ctx.closePath();
ctx.fillStyle = "#2E17FE";
ctx.fill();
ctx.stroke();
ctx.beginPath();
ctx.moveTo(1000,0);
ctx.lineTo(750,0);
ctx.lineTo(550,100);
ctx.lineTo(1000,100);
ctx.closePath();
ctx.fillStyle = "#FD3232";
ctx.fill();
ctx.stroke();
ctx.font = "30px Arial";
ctx.textAlign = "center";
ctx.fillStyle = "white";
ctx.fillText("Who I Am", c.width/2 , c.height/2);
